# Generated by Django 4.2.21 on 2025-06-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicrecommendation_user_uploadedimage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicrecommendation',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
